#!/bin/sh
set -xe
USER="tester"
PASSWD="testpwd"
GERRIT="http://gerrit-httpd"
CURL="curl -v -u $USER:$PASSWD"

put(){
    $CURL -X PUT -H "Content-Type: application/json;charset=utf-8" "$@"
}

export HOME=/home/$USER
cd $HOME

# this will create the account if it doesn't exist yet
curl -v -u $USER:$PASSWD $GERRIT/login/

put -d '{"name":"test user"}' $GERRIT/a/accounts/self/name